name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
          
      - uses: actions/checkout@v3
          
      - name: install
        run: npm install 
      
      - name: test 
        run: npm run test
        env:
          CI: true
      
      - name: build 
        run: npm run build
